int PRICE_OF_SOVEREIGN = 495;
int PRICE_OF_20FRANCS = 400;
int PRICE_OF_QUARTER_OUNCE = 556;
int PRICE_OF_HALF_OUNCE = 1150;
int PRICE_OF_WHOLE_OUNCE = 2100;
int SILVER_PRICE = 25;

int STARTING_PRINCIPAL;

int SAVINGS_ACCT_INTEREST_RATE;
int BOND_INTEREST_RATE;

int SPY_APPRECIATION;
int SPY_YIELD;
int VYM_YIELD;
int VYM_APPRECIATION;
int SCHD_YIELD;
int SCHD_APPRECIATION;
int _APPRECIATION;
int _YIELD;



void main()
{
    establishValues();

}
main();